# Generated by Django 5.1.1 on 2024-10-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corestudent',
            name='register_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
