# Generated by Django 5.1.1 on 2024-11-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0008_result'),
        ('core', '0003_corestudent_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='corestudent',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordinator.house'),
        ),
    ]
