# Generated by Django 5.1.1 on 2024-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_corestudent_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='corestudent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
