# Generated by Django 5.1.1 on 2024-10-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='assigned_events',
        ),
    ]
