# Generated by Django 5.1.1 on 2024-10-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_coordinator_assigned_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorAssignedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.coordinator')),
                ('sport_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.sportevent')),
            ],
            options={
                'unique_together': {('coordinator', 'sport_event')},
            },
        ),
    ]
