# Generated by Django 5.1.1 on 2024-10-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_coordinatorassignedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.coordinator'),
        ),
    ]
