# Generated by Django 5.1.1 on 2024-10-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_coordinatorassignedevent'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assigned_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='admin_panel.coordinator')),
            ],
        ),
    ]
