# Generated by Django 5.1.1 on 2024-10-31 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_sportevent_coordinator'),
        ('coordinator', '0003_fixtureresult'),
        ('student', '0004_eventregistration_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='admin_panel.sportevent')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_fixtures', to='student.eventregistration')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_fixtures', to='student.eventregistration')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_wins', to='student.eventregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='FixtureResult',
        ),
    ]
