# Generated by Django 5.1.1 on 2024-10-31 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_remove_matchfixture_student_1_score_and_more'),
        ('core', '0002_corestudent_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfixture',
            name='student_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchfixture',
            name='student_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchfixture',
            name='student_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_student_1', to='core.corestudent'),
        ),
        migrations.AlterField(
            model_name='matchfixture',
            name='student_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_student_2', to='core.corestudent'),
        ),
        migrations.AlterField(
            model_name='matchfixture',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_matches', to='core.corestudent'),
        ),
    ]
