# Generated by Django 5.1.1 on 2024-11-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0009_certificate'),
        ('core', '0004_corestudent_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_achieved', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='coordinator.result')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.corestudent')),
            ],
        ),
    ]
