# Generated by Django 5.1.1 on 2024-10-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_house'),
        ('core', '0001_initial'),
        ('student', '0002_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='house_name',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coordinator.house'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.corestudent'),
        ),
    ]
