# Generated by Django 5.1.1 on 2024-11-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_eventregistration_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
